### ISSUE TITLE
Plugin calls for image that doesn't exist

### ISSUE THREAD

**Issue by marcscheff** [pelmered/WooCommerce-Better-Product-Thumbnail-Navigation#1]
Hi!

I installed the better product thumbnail plugin and have a couple minor issues.
1. When I click a thumbnail, I get a broken image in the main thumbnail area. I looked at the source and it seems to be looking for a version of my image that looks like IMAGENAME-800x800.jpg. This doesn't exist for most of my thumbnails. What is the best way to either tweak your code to find an existing large image and resize, or create an "-800x800.jpg" version for all images on my site?
2. How do I activate the lightbox feature to show a large version of the 800x800 image in a lightbox?

thanks!
-Marc
http://www.everydayoriginal.com (plugin now deactivated because this is a live site that depends on people seeing the images)

**Comment by bitnerdesign** [comment]
I was having the same issue. I had to go to WooCommerce Settings > Products > Display then change Single Product Image to 800 x 800 with hard crop. Install and run Regenerate Thumbnails plugin and then it worked. Hope this helps! http://wordpress.org/extend/plugins/regenerate-thumbnails/

**Comment by marcscheff** [comment]
I'll give it a shot!
- Marc

---

MARC SCHEFF / Art & Direction

Portfolio http://www.marcscheff.com/  |  Instagram
http://instagram.com/marcscheff | Every Day Original
http://www.everydayoriginal.com/

**Comment by marcscheff** [comment]
Ok, I tried this, ran regen twice, still getting a broken link in the main
image when I click. My original images are also 800x800...
- Marc

---

MARC SCHEFF / Art & Direction

Portfolio http://www.marcscheff.com/  |  Instagram
http://instagram.com/marcscheff | Every Day Original
http://www.everydayoriginal.com/

**Comment by pelmered** [comment]
Hello @marcscheff,

Thank you for the report, I'm sorry for the late reply. 

This seams strange, to regenerate the thumbnails should help. Does the image you are requesting exist in the filesystem?

The Lightbox feature can be a bit buggy with some themes. What theme are you using? It also requires the built in Lightbox in WooCommerce to be activated. I think there is a checkbox for that somewhere in the settings.

**Comment by marcscheff** [comment]
I'm using theonepager and have tried lightbox in woo commerce and the
theme. And regened multiple times. _shrug_

**Comment by adamkinder** [comment]
I managed to fix this by amending the code on line 103

$('.woocommerce-main-image img').attr('src', $src.replace('-<?php echo $product_thumbnail_size; ?>','-<?php echo $product_single_image_size; ?>'));

I removed -<?php echo $product_single_image_size; ?> from the line so it just reads as '' now. This means that the main image file isn't looking for a specific size, it now just looks for the main image src.

Edit : my line 103 now reads as $('.woocommerce-main-image img').attr('src', $src.replace('-<?php echo $product_thumbnail_size; ?>',''));

**Comment by pelmered** [comment]
Hm, I will see if I can reproduce this...

What Themes are you using other than The One Pager? I don't have that licence.
