### ISSUE TITLE
Plugin to work with wordpress 4.4 and srcset.

### ISSUE THREAD

**Issue by olleka** [pelmered/WooCommerce-Better-Product-Thumbnail-Navigation#3]
Hi
Add these lines below line 103 in the
$srcset = $this.attr('srcset');
$('.woocommerce-main-image').attr('href', $srcset);
$('.woocommerce-main-image img').attr('srcset', $srcset.replace('-<?php echo $product_thumbnail_size; ?>','-<?php echo $product_single_image_size; ?>'));

Regards
Olle Karneman

**Comment by pelmered** [comment]
Hello, 

Thank you for the code. I will review this the comming week and it will probably be included in next version one way or another.

**Comment by pelmered** [comment]
I have merged the PR. I will update the plugin in wordpress.org in the as soon as possible. I have an other issue to resolve.

**Comment by tarranjones** [comment]
1+, was about to suggest this, 

`$('.woocommerce-main-image').attr('href')` is set twice, assuming `$srcset` is always set them `$('.woocommerce-main-image').attr('href', $src);` can be removed.

**Comment by tarranjones** [comment]
If "Enable Lightbox for product images" is unchecked then you get the following console error, `Uncaught TypeError: Cannot read property 'open' of undefined`

This should fix it. 

```
        if($.prettyPhoto){
            $.prettyPhotasdo.open(photoGalleryImages,photoGalleryTitles);
        }
```
